name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  whisper-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']  # ['3.10', '3.12', '3.13']
        pytorch-version: [2.9.1] # [2.5.1, 2.9.1]
        exclude:
          - python-version: '3.12'
            pytorch-version: 2.5.1
    steps:
      - uses: actions/checkout@v4
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          use-mamba: true
          python-version: ${{ matrix.python-version }}
      - run: conda install -n test ffmpeg
      - run: echo "$CONDA/envs/test/bin" >> $GITHUB_PATH
      - name: Install Pytorch
        run: pip install torch==${{ matrix.pytorch-version }} torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
      - run: pip install .["dev"]
      - run: black --check --diff -t py38 --include '(\.pyi?)$' .
      - run: isort --check --diff .
      - run: flake8 --ignore E203,W503,W504,E501,E731,E741 .
      - run: pytest --durations=0 -vv -k 'not test_transcribe or test_transcribe[tiny] or test_transcribe[tiny.en]' -m 'not requires_cuda'
